CREATE TABLE C_USUARIO(
	ID NUMBER(10) NOT NULL,
	NOMBRE VARCHAR2(100) NOT NULL,
	EMAIL VARCHAR2(255) NOT NULL,
	EDAD NUMBER(3,0) NOT NULL,
	PASSWORD VARCHAR2(50) NOT NULL
);
ALTER TABLE C_USUARIO ADD(
	CONSTRAINT c_dept_pk PRIMARY KEY(ID)
);
ALTER TABLE C_USUARIO ADD
	CONSTRAINT c_uq_usuario_email UNIQUE(EMAIL)
;
CREATE SEQUENCE c_dept_seq START WITH 1;
CREATE OR REPLACE TRIGGER c_dept_bir
	BEFORE INSERT ON C_USUARIO
	FOR EACH ROW
	
	BEGIN
		SELECT c_dept_seq.NEXTVAL
		INTO :new.id
		FROM dual;
	END;