CREATE TABLE USUARIO(
	ID NUMBER(10) NOT NULL,
	NOMBRE VARCHAR2(100) NOT NULL,
	EMAIL VARCHAR2(255) NOT NULL,
	EDAD NUMBER(3,0) NOT NULL,
	PASSWORD VARCHAR2(50) NOT NULL
);
ALTER TABLE USUARIO ADD(
	CONSTRAINT dept_pk PRIMARY KEY(ID)
);
ALTER TABLE USUARIO ADD
	CONSTRAINT uq_usuario_email UNIQUE(EMAIL)
;
CREATE SEQUENCE dept_seq START WITH 1;
CREATE OR REPLACE TRIGGER dept_bir
	BEFORE INSERT ON USUARIO
	FOR EACH ROW
	
	BEGIN
		SELECT dept_seq.NEXTVAL
		INTO :new.id
		FROM dual;
	END;
	
INSERT INTO usuario (nombre, email, edad, password) VALUES ('Pepe', 'pepe@gmai.com', 19, 'pepe');

ALTER TABLE USUARIO ADD APELLIDOS VARCHAR(50);
ALTER TABLE USUARIO ADD FECHA_REGISTRO DATE;
ALTER TABLE USUARIO ADD DESCRIPCION VARCHAR(100) DEFAULT 'Un vago como todos';

